# Generated by Django 5.2.5 on 2025-10-01 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='адрес')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата последней проверки')),
            ],
            options={
                'verbose_name': 'координаты',
                'verbose_name_plural': 'координаты',
                'indexes': [models.Index(fields=['address'], name='coordinates_address_357991_idx'), models.Index(fields=['created_at'], name='coordinates_created_5739dc_idx')],
            },
        ),
    ]
