services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: star_burger
      POSTGRES_USER: star_burger_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U star_burger_user -d star_burger"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - static_volume:/app/staticfiles
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
  static_volume:
