# Generated by Django 5.2.5 on 2025-09-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='foodcartapp_status_00a082_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber'], name='foodcartapp_phonenu_5f4ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['lastname', 'firstname'], name='foodcartapp_lastnam_a2dab6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['address'], name='foodcartapp_address_ce2813_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='foodcartapp_created_cd8d79_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['called_at'], name='foodcartapp_called__a766dd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivered_at'], name='foodcartapp_deliver_0afa88_idx'),
        ),
    ]
