# Generated by Django 5.2.5 on 2025-09-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_order_foodcartapp_status_00a082_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='foodcartapp.restaurant', verbose_name='ресторан для приготовления'),
        ),
    ]
