# Generated by Django 5.2.7 on 2025-10-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_assigned_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('online', 'Онлайн')], db_index=True, default='cash', max_length=20, verbose_name='способ оплаты'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method'], name='foodcartapp_payment_2918c1_idx'),
        ),
    ]
