# Generated by Django 5.2.7 on 2025-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('online', 'Онлайн')], db_index=True, max_length=20, verbose_name='способ оплаты'),
        ),
    ]
